* add support for podman as an alternative to docker for containerization

diff --git a/zde b/zde
--- a/zde
+++ b/zde
@@ -14,16 +14,21 @@ COMMAND=$1
 shift
 
 RUNNING="1"
+CONTAINER_CMD=docker
 CONTAINER_NAME=zeal8bit
 COMPOSE_PATH="$ZDE_PATH/docker-compose.yml"
 export ZDE_IMAGE=zoul0813/zeal-dev-environment
 export ZDE_VERSION="${ZDE_VERSION:=latest}"
 # export ZDE_PLATFORM=linux/amd64
 if command -v docker 2>&1 >/dev/null; then
-  docker ps --filter "name=$CONTAINER_NAME" | grep -q "$CONTAINER_NAME"
+  $CONTAINER_CMD ps --filter "name=$CONTAINER_NAME" | grep -q "$CONTAINER_NAME"
+  RUNNING=$?
+elif command -v podman 2>&1 >/dev/null; then
+  CONTAINER_CMD=podman
+  $CONTAINER_CMD ps --filter "name=$CONTAINER_NAME" | grep -q "$CONTAINER_NAME"
   RUNNING=$?
 else
-  echo "WARNING: docker not found, ensure docker is installed before using ZDE"
+  echo "WARNING: docker/podman not found, ensure docker, or podman, is installed before using ZDE"
 fi
 
 emulator()
@@ -47,27 +52,27 @@ emulator()
 emulator_start()
 {
   # supervisord -c /etc/supervisord.conf
-  docker exec -t zeal8bit supervisorctl status emulator
+  $CONTAINER_CMD exec -t zeal8bit supervisorctl status emulator
   STATUS=$?
   if [ "$STATUS" = "3" ]; then
-    docker exec -t zeal8bit supervisorctl start emulator
+    $CONTAINER_CMD exec -t zeal8bit supervisorctl start emulator
   fi
   PATH=$PATH:"$ZDE_PATH"/bin "$ZDE_PATH"/bin/xdg-open "http://127.0.0.1:1145/?r=latest&$1"
 }
 
 emulator_stop()
 {
-  docker exec -t zeal8bit supervisorctl status emulator
+  $CONTAINER_CMD exec -t zeal8bit supervisorctl status emulator
   STATUS=$?
   if [ "$STATUS" = "0" ]; then
-    docker exec -t zeal8bit supervisorctl stop emulator
+    $CONTAINER_CMD exec -t zeal8bit supervisorctl stop emulator
   fi
 }
 
 stop()
 {
   if [ "$RUNNING" = "0" ]; then
-    docker compose -f "$COMPOSE_PATH" stop
+    $CONTAINER_CMD compose -f "$COMPOSE_PATH" stop
     rm ~/.zde/mount
     RUNNING="1"
   else
@@ -78,7 +83,7 @@ stop()
 start()
 {
   if [ "$RUNNING" = "1" ]; then
-    docker compose -f "$COMPOSE_PATH" up -d
+    $CONTAINER_CMD compose -f "$COMPOSE_PATH" up -d
     echo $PWD > ~/.zde/mount
     RUNNING="0"
   else
@@ -104,13 +109,13 @@ make_image()
   shift
   case $TYPE in
     eeprom)
-      docker exec -t $CONTAINER_NAME /home/zeal8bit/zsync.sh eeprom ${SIZE:=32}
+      $CONTAINER_CMD exec -t $CONTAINER_NAME /home/zeal8bit/zsync.sh eeprom ${SIZE:=32}
       ;;
     cf)
-      docker exec -t $CONTAINER_NAME /home/zeal8bit/zsync.sh cf ${SIZE:=64}
+      $CONTAINER_CMD exec -t $CONTAINER_NAME /home/zeal8bit/zsync.sh cf ${SIZE:=64}
       ;;
     sd)
-      docker exec -t $CONTAINER_NAME /home/zeal8bit/zsync.sh sd ${SIZE:=64}
+      $CONTAINER_CMD exec -t $CONTAINER_NAME /home/zeal8bit/zsync.sh sd ${SIZE:=64}
       ;;
     *)
       echo "Invalid arguments, must provide TYPE (eeprom, cf, sd)"
@@ -128,7 +133,7 @@ case $COMMAND in
     git -C "$ZDE_PATH" checkout main
     git -C "$ZDE_PATH" submodule init
     git -C "$ZDE_PATH" pull --recurse-submodules origin main
-    docker image pull ${ZDE_IMAGE}:${ZDE_VERSION}
+    $CONTAINER_CMD image pull ${ZDE_IMAGE}:${ZDE_VERSION}
     if [ "$RESTART" = "0" ]; then
       start
     fi
@@ -161,24 +166,24 @@ case $COMMAND in
       make -f "$ZDE_PATH/home/zeal-game-dev-kit/aseprite.mk"
     fi
     if [ "$RUNNING" = "0" ]; then
-      docker exec --env-file="$ZDE_PATH/.env" -t $CONTAINER_NAME make $@
+      $CONTAINER_CMD exec --env-file="$ZDE_PATH/.env" -t $CONTAINER_NAME make $@
     else
       echo "ZDE is not running"
     fi
     ;;
   create)
-    docker run --rm -v .:/tmp -v $ZDE_PATH/home:/home/zeal8bit --env-file=$ZDE_PATH/.env $ZDE_IMAGE:$ZDE_VERSION /home/zeal8bit/templates/create.sh "$@"
+    $CONTAINER_CMD run --rm -v .:/tmp -v $ZDE_PATH/home:/home/zeal8bit --env-file=$ZDE_PATH/.env $ZDE_IMAGE:$ZDE_VERSION /home/zeal8bit/templates/create.sh "$@"
     ;;
   image)
     make_image $@
     ;;
   rebuild)
     if [ "$RUNNING" = "0" ]; then
-      docker compose -f "$COMPOSE_PATH" down
+      $CONTAINER_CMD compose -f "$COMPOSE_PATH" down
     fi
-    docker compose -f "$COMPOSE_PATH" build
+    $CONTAINER_CMD compose -f "$COMPOSE_PATH" build
     ;;
   *)
-    echo "Help: update, status, start, stop, make"
+    echo "Help: update, status, start, stop, make, emu[lator], create, image"
     ;;
 esac
